#!/bin/bash
set -e 

TUBA_PATH="$HOME/tuba-seq/bin"      # PATH to tuba-seq executables
DATA_DIR=`pwd`                      # Directory containing the fastq files (defaults to current working directory)
MERGE_DIR='merged_reads'            # Directory name for merged forward/reverse reads.

FORWARD_READS="forward_reads"
REVERSE_READS="reverse_reads"

echo "Analyzing paired-end fastq files in $DATA_DIR."

cd $DATA_DIR;
$TUBA_PATH/PEAR.py -p -m $MERGE_DIR $FORWARD_READS $REVERSE_READS;
$TUBA_PATH/preprocess.py -p -s -f 0.01 $MERGE_DIR;
$TUBA_PATH/DADA2_error_training.R training_derep.RData >> DADA2_error_training.LOG;

echo "All preprocessing completed. If the error training output stats and the fraction of cluster-able reads look good, then you are ready for clustering.";
echo "This task ought to be broadcasted onto a cluster.";
echo "See DADA2_clustering.R for details."

