#!/bin/bash
set -ex 

TUBA_PATH="$HOME/tuba-seq/bin"      # PATH to tuba-seq executables
DATA_DIR=`pwd`                      # Directory containing the fastq files (defaults to current working directory)
MERGE_DIR='merged_reads'            # Directory name for merged forward/reverse reads.

FORWARD_READS="forward_reads"
REVERSE_READS="reverse_reads"

cd $DATA_DIR;
$TUBA_PATH/PEAR.py -p -m $MERGE_DIR $FORWARD_READS $REVERSE_READS;
$TUBA_PATH/preprocess.py -p -s --symmetric_flanks --trim=10 -d $MERGE_DIR;
$TUBA_PATH/DADA2_error_training.R training/ >> DADA2_error_training.LOG;

set +x
GREEN='\033[0;32m'
NC='\033[0m'
echo -e "${GREEN}Preprocessing completed successfully.${NC}" 
echo "If the error training output stats and the fraction of cluster-able reads look good, then you are ready for clustering.";
echo "This task ought to be broadcasted onto a cluster.";
echo "See DADA2_clustering.R for details."

