#!/bin/bash
set -ex 

FILE="IW3098.fastq.gz"       #$1

TUBA_PATH="$HOME/tuba-seq/bin"      # PATH to tuba-seq executables
DATA_DIR=`pwd`                      # Directory containing the fastq files (defaults to current working directory)
MERGE_DIR='merged_reads'            # Directory name for merged forward/reverse reads.

FORWARD_READS="forward_reads"
REVERSE_READS="reverse_reads"
MEMORY="4G"

TALLY_DIR="mutation_tallies"

cd $DATA_DIR;
SAMPLE=${FILE%.fastq*}
echo "Processing $FILE"
#$TUBA_PATH/PEAR.py --single --uncompressed --memory=$MEMORY -m $MERGE_DIR $FORWARD_READS/$FILE $REVERSE_READS/$FILE;
$TUBA_PATH/preprocess.py --search_blast -f=0.05 --single --symmetric_flanks -d $MERGE_DIR/$SAMPLE.fastq;

set +x
echo "All preprocessing completed. If the error training output stats and the fraction of cluster-able reads look good, then you are ready for clustering.";
echo "This task ought to be broadcasted onto a cluster.";
echo "See DADA2_clustering.R for details."

