#!/bin/bash
set -e

TUBA_PATH=$HOME/tuba-seq

$TUBA_PATH/unadulterated/preprocess.py

gunzip training/*.gz
gunzip preprocessed/*.gz

$TUBA_PATH/unadulterated/DADA2_derep.R ./
$TUBA_PATH/DADA2_error_training.R training 2&1>> DADA2_error_training.LOG

